import org.clulab.processors.fastnlp.FastNLPProcessor
import org.clulab.processors.shallownlp.ShallowNLPProcessor

/**
  *
  * User: mihais
  * Date: 10/1/14
  */
object Test2Example {

  def main(args: Array[String]): Unit = {
    //    var done = false
    //    var bufferedSource = Source.fromFile("C:\\Users\\vendovitskaya\\PycharmProjects\\parexel-aid\\data\\processed\\odin\\backward_rules\\auto_rules_1_pos_no_symptoms.yaml")
    //    val rules = bufferedSource.mkString
    //    val engine = ExtractorEngine(rules)
    var proc = new FastNLPProcessor(withDiscourse = ShallowNLPProcessor.NO_DISCOURSE)
    val documents = proc.annotate("blah", keepText = true)
    var i = scala.io.StdIn.readLine()
    while (i != "i") {
      i = scala.io.StdIn.readLine()
    }
    //  var t =  List.apply(" histologically confirmed kaposis sarcoma requiring chemotherapy and/or currently  being treated with paclitaxel serologic diagnosis of hiv infection documented by a positive elisa and confirmed with  a western blot or other federally approved hiv diagnostic test patient characteristics: age: 18 and over performance status: ecog 0-2 life expectancy: not specified hematopoietic: absolute neutrophil count at least 1 000/mm ^3 with or without the use of  colony-stimulating factors  platelet count at least 50 000/mm^3 hepatic: bilirubin no greater than 1.5 times upper limit of normal uln  ast no greater than 2.5 times uln alkaline phosphatase no greater than 2.5 times uln renal: creatinine no greater than 1.5 mg/dl or creatinine clearance greater than 60 ml/min neurologic: no greater than grade 2 peripheral neuropathy no neuropsychiatric history or altered mental status that would preclude study other: not pregnant or nursing fertile patients must use effective contraception no other prior or concurrent malignancy except curatively treated carcinoma in situ of  the cervix or basal cell or squamous cell skin cancer no sensitivity to e. coli-derived proteins no active untreated infection no new infectious complications requiring a change in antibiotics within the past 2  weeks prior concurrent therapy: biologic therapy: not specified chemotherapy: see disease characteristics endocrine therapy: not specified radiotherapy: at least 1 week since prior radiotherapy no prior radiotherapy to marker lesions no concurrent radiotherapy surgery: not specified other: at least 2 weeks since prior systemic treatment for kaposis sarcoma at least 2 weeks since prior nonapproved fda investigational agents except available  investigational new drugs that are antiretroviral agents concurrent maintenance therapy for opportunistic infections allowed concurrent commercially available antiretroviral therapy allowed ",
    //  " histologically confirmed kaposis sarcoma requiring chemotherapy and/or currently  being treated with paclitaxel serologic diagnosis of hiv infection documented by a positive elisa and confirmed with  a western blot or other federally approved hiv diagnostic test patient characteristics: age: 18 and over performance status: ecog 0-2 life expectancy: not specified hematopoietic: absolute neutrophil count at least 1 000/mm ^3 with or without the use of  colony-stimulating factors  platelet count at least 50 000/mm^3 hepatic: bilirubin no greater than 1.5 times upper limit of normal uln  ast no greater than 2.5 times uln alkaline phosphatase no greater than 2.5 times uln renal: creatinine no greater than 1.5 mg/dl or creatinine clearance greater than 60 ml/min neurologic: no greater than grade 2 peripheral neuropathy no neuropsychiatric history or altered mental status that would preclude study other: not pregnant or nursing fertile patients must use effective contraception no other prior or concurrent malignancy except curatively treated carcinoma in situ of  the cervix or basal cell or squamous cell skin cancer no sensitivity to e. coli-derived proteins no active untreated infection no new infectious complications requiring a change in antibiotics within the past 2  weeks prior concurrent therapy: biologic therapy: not specified chemotherapy: see disease characteristics endocrine therapy: not specified radiotherapy: at least 1 week since prior radiotherapy no prior radiotherapy to marker lesions no concurrent radiotherapy surgery: not specified other: at least 2 weeks since prior systemic treatment for kaposis sarcoma at least 2 weeks since prior nonapproved fda investigational agents except available  investigational new drugs that are antiretroviral agents concurrent maintenance therapy for opportunistic infections allowed concurrent commercially available antiretroviral therapy allowed ")
    //  var proc = new FastNLPProcessor(withDiscourse = ShallowNLPProcessor.NO_DISCOURSE)
    val documents1 = proc.annotate(
      " histologically confirmed kaposis sarcoma requiring chemotherapy and/or currently  being treated with paclitaxel serologic diagnosis of hiv infection documented by a positive elisa and confirmed with  a western blot or other federally approved hiv diagnostic test patient characteristics: age: 18 and over performance status: ecog 0-2 life expectancy: not specified hematopoietic: absolute neutrophil count at least 1 000/mm ^3 with or without the use of  colony-stimulating factors  platelet count at least 50 000/mm^3 hepatic: bilirubin no greater than 1.5 times upper limit of normal uln  ast no greater than 2.5 times uln alkaline phosphatase no greater than 2.5 times uln renal: creatinine no greater than 1.5 mg/dl or creatinine clearance greater than 60 ml/min neurologic: no greater than grade 2 peripheral neuropathy no neuropsychiatric history or altered mental status that would preclude study other: not pregnant or nursing fertile patients must use effective contraception no other prior or concurrent malignancy except curatively treated carcinoma in situ of  the cervix or basal cell or squamous cell skin cancer no sensitivity to e. coli-derived proteins no active untreated infection no new infectious complications requiring a change in antibiotics within the past 2  weeks prior concurrent therapy: biologic therapy: not specified chemotherapy: see disease characteristics endocrine therapy: not specified radiotherapy: at least 1 week since prior radiotherapy no prior radiotherapy to marker lesions no concurrent radiotherapy surgery: not specified other: at least 2 weeks since prior systemic treatment for kaposis sarcoma at least 2 weeks since prior nonapproved fda investigational agents except available  investigational new drugs that are antiretroviral agents concurrent maintenance therapy for opportunistic infections allowed concurrent commercially available antiretroviral therapy allowed ",
      keepText = true
    )
    println(s"Done! Loaded documents.")
    while (true) {}
  }
}
